name: Release

on:
  release:
    types: [published]
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: write client ID into local.properties
          uses: christian-draeger/write-properties@1.0.1
          with:
            path: './local.properties'
            property: 'com.storyous.delivery.LoginClientId'
            value: ${{ secrets.LOGIN_CLIENT_ID }}
      - name: write client secret into local.properties
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './local.properties'
          property: 'com.storyous.delivery.LoginClientSecret'
          value: ${{ secrets.LOGIN_CLIENT_SECRET }}
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Sign release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.KEY_JKS }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release-unsigned-signed.apk
