name: Release

on:
  release:
    types: [published]
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: write client ID into local.properties
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './local.properties'
          property: 'com.storyous.delivery.LoginClientId'
          value: ${{ secrets.LOGIN_CLIENT_ID }}
      - name: Build release APK
        shell: bash
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run:
          echo "$KEY_JKS" > app/keystore.b64 && base64 --decode app/keystore.b64 > app/keystore.jks && pwd && ./gradlew assembleRelease bundleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: app/build/outputs/bundle/release/app-release.aab
